bankproject/bankapp/urls.py
from . import views
from django.urls import path

app_name = 'bankapp'

urlpatterns = [
     path('', views.home,name='home'),
     path('login/', views.login,name='login'),
     path('register/', views.register,name='register'),
     path('register_form/',views.register_form,name='register_form'),
     path('submit_form/',views.submit_form,name='submit_form'),
     path('logout/',views.logout,name='logout'),
     path('success_page/',views.success_page,name='success_page'),

]

bankproject/bankproject/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('bankapp.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

bankproject/bankapp/models.py
from django import forms
from django.db import models


# Create your models here.
class Registration(models.Model):
    username = models.CharField(max_length=100)
    password = models.CharField(max_length=255)  # Adjust the max length accordingly
    confirm_password = models.CharField(max_length=255)


def _str_(self):
    return self.username


class District(models.Model):
    name = models.CharField(max_length=100)

    def _str_(self):
        return self.name


class Branch(models.Model):
    name = models.CharField(max_length=100)
    district = models.ForeignKey(District, on_delete=models.CASCADE)
    wikipedia_link = models.URLField()

    def _str_(self):
        return self.name


class AccountType(models.Model):
    name = models.CharField(max_length=100)

    def _str_(self):
        return self.name


class Material(models.Model):
    name = models.CharField(max_length=100)

    def _str_(self):
        return self.name


class Personnal(models.Model):
    name = models.CharField(max_length=100)
    dob = models.DateField()
    age = models.IntegerField()
    gender = models.CharField(max_length=10, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')])
    phonenumber = models.CharField(max_length=10,null=False)
    mailid = models.EmailField(null=False)
    address = models.TextField(max_length=100)
    district = models.ForeignKey(District, on_delete=models.CASCADE)
    branch = models.ForeignKey(Branch, on_delete=models.CASCADE)
    AccountType = models.ForeignKey(AccountType, on_delete=models.CASCADE,
                                     choices=[('savings Account', 'Savings account'),
                                              ('current account', 'Current account'),
                                              ('other', 'Other')])
    materials_provide1 = models.CharField(max_length=100)
    materials_provide2 = models.CharField(max_length=100)
    materials_provide3 = models.CharField(max_length=100)

    def _str_(self):
        return self.name

bankproject/bankapp/views.py
from django.contrib.auth.models import User
from django.contrib import messages, auth
from django.http import HttpResponse, HttpResponseRedirect

from .models import Registration, Personnal, District, Branch, AccountType
from django.shortcuts import render, redirect


def home(request):
    return render(request, 'Home.html')


def login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = auth.authenticate(request, username=username, password=password)
        if user is not None:
            auth.login(request, user)

        else:
            return render(request, 'login.html',
                          {'message': "Username or password is incorrect"})

        return redirect('bankapp:success_page')
    return render(request, "login.html")


def register(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        confirmpassword = request.POST.get('confirm_password')
        if password == confirmpassword:
            if User.objects.filter(username=username).exists():
                return render(request, 'register.html',
                              {'message': "Username already exists."})
            else:
                user = User.objects.create_user(username=username, password=password)
                user.save()
                Registration.objects.create(username=username, password=password)
        else:

            return render(request, 'register.html', {'message': "Passwords do not match."})
        return redirect('bankapp:login')

    return render(request, 'register.html')


def register_form(request):
    if request.method == 'POST':
        name = request.POST.get('name')
        dob = request.POST.get('dob')
        age = request.POST.get('age')
        gender = request.POST.get('gender')
        phonenumber = request.POST.get('phonenumber')
        mailid = request.POST.get('mailid')
        address = request.POST.get('address')
        district = request.POST.get('district')
        branch = request.POST.get('branch')
        AccountType = request.POST.get('AccountType')
        materials_provide1 = request.POST.get('materials_provide1')
        materials_provide2 = request.POST.get('materials_provide1')
        materials_provide3 = request.POST.get('materials_provide3')
        return redirect('bankapp:submit_form')
    return render(request, 'register_form.html')


def submit_form(request):
    if request.method == 'POST':

        confirmation_message = 'Order Confirmed'
        return render(request, 'submit_form.html', {'confirmation_message': confirmation_message})
    else:
        return render(request, 'submit_form.html')


def success_page(request):
    return render(request, 'success_page.html')


def logout(request):
    auth.logout(request)
    return redirect('/')

bankproject/templates/Home.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<div class="background-image">
    <div class="box">


        <img src="{% static 'image/banner.jpg' %}" alt="Background Image">
<div class="button">
            <a href="{% url 'bankapp:login' %}" class="btn btn-block">GO TO LOGIN</a>
        </div>
    </div>


    </div>


{% endblock %}

bankproject/templates/base.html
{%  load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="{% static 'D:\django\bank_project\bankproject\static\css\style.css' %}">

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css">
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>
    <script src="/static/js/popper.min.js"></script>
    <script src="/static/js/bootstrap.min.js"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'static/css/style.css' %}">
    <title>{%  block title %}{%  endblock %}</title>
</head>
<body>
<div class="container">
    {% include 'navbar.html' %}
    {% block content %}
    {% endblock %}
</div>
<script src="{% static 'js/popper.min.js' %}" ></script>
<script src="{% static 'js/bootstrap.min.js' %}" ></script>
</body>
</html>

bankproject/templates/login.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="wrapper">
  <h2 class="title">LOGIN</h2>
</div>

  <form method="post" action="">
    {% csrf_token %}

    <div class="log">
        <label for="username"></label>
        <input type="text" id="username" name="username" placeholder="Username" required>
        <br>
        <label for="password"></label>
        <input type="password" id="password" name="password" placeholder="Password" required>

    </div>
      <br>


    <button type="submit" class="btn btn-success">Login</button>

      {% if message %}
          <p>{{ message }}</p>
      {% endif %}
  </form>


  <p>Don't have an account? <a href="{% url 'bankapp:register' %}">Register here</a></p>

{% endblock %}

bankproject/templates/navbar.html
<nav class="navbar navbar-expand-lg">
<a class="navbar-brand" href="#">BANKING</a>
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'bankapp:home' %}">Home</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'bankapp:register' %}">Register</a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'bankapp:login' %}">Login</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Branch
          </a>
          <ul class="dropdown-menu">

           <li><a class="dropdown-item" href="https://en.wikipedia.org/wiki/Thiruvananthapuram_district">Thiruvananthapuram</a></li>
<li><a class="dropdown-item" href="https://en.wikipedia.org/wiki/Kollam_district">Kollam</a></li>
<li><a class="dropdown-item" href="https://en.wikipedia.org/wiki/Pathanamthitta_district">Pathanamthitta</a></li>
<li><a class="dropdown-item" href="https://en.wikipedia.org/wiki/Alappuzha_district">Alappuzha</a></li>
<li><a class="dropdown-item" href="https://en.wikipedia.org/wiki/Kottayam_district">Kottayam</a></li>
<li><a class="dropdown-item" href="https://en.wikipedia.org/wiki/Idukki_district">Idukki</a></li>
<li><a class="dropdown-item" href="https://en.wikipedia.org/wiki/Ernakulam_district">Ernakulam</a></li>
<li><a class="dropdown-item" href="https://en.wikipedia.org/wiki/Thrissur_district">Thrissur</a></li>
<li><a class="dropdown-item" href="https://en.wikipedia.org/wiki/Palakkad_district">Palakkad</a></li>
<li><a class="dropdown-item" href="https://en.wikipedia.org/wiki/Malappuram_district">Malappuram</a></li>
<li><a class="dropdown-item" href="https://en.wikipedia.org/wiki/Kozhikode_district">Kozhikode</a></li>
<li><a class="dropdown-item" href="https://en.wikipedia.org/wiki/Wayanad_district">Wayanad</a></li>
<li><a class="dropdown-item" href="https://en.wikipedia.org/wiki/Kannur_district">Kannur</a></li>
<li><a class="dropdown-item" href="https://en.wikipedia.org/wiki/Kasaragod_district">Kasaragod</a></li>


          </ul>
        </li>
      </ul>
      <ul class="navbar-nav ms-auto">
        <li class="nav-item" style="margin-top: 10px;">
        <br>
          {% if user.is_authenticated %}

              <li style="color: darkblue;  padding-top: 7px;">{{ user.username }}</li>

            <a href="{% url 'bankapp:logout' %}" class="btn btn-block">Logout</a>
          {% else %}
            <li><a href="{% url 'bankapp:register' %}"></a></li>

            <li><a class="navbar-brand" href="{% url 'bankapp:login' %}"></a></li>
          {% endif %}

      </ul>
    </div>
  </div>
</nav>
project

bankproject/templates/register.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <div class="reg_wrapper">
<h2>REGISTER</h2>
    </div>

  <form method="post" action="">
    {% csrf_token %}
  <div class="reg_input">
    <label for="username"></label>
    <input type="text" id="username" name="username"  placeholder="Username" required>
  </div>
<div class="reg_inp">
    <label for="password"></label>
    <input type="password" id="password" name="password" placeholder="Password" required>
</div>

  <div class="reg_in">
    <label for="confirm_password"></label>
    <input type="password" id="confirm_password" name="confirm_password" placeholder="Confirm Password" required>
  </div>
    <br>

   <button type="submit" class="btn btn-primary">Register</button>
  <br>
      {% if message %}
    <p>{{ message }}</p>
{% endif %}
  </form>

  <p>Already have an account? <a href="{% url 'bankapp:login' %}">Login here</a></p>
{% endblock %}

bankproject/templates/register_form.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<h2>REGISTER</h2>
  <form method="POST"  action="">
    {% csrf_token %}

      <div class="container ">
      <div class="box-1">
 <div class="name">
  <label>
        <input type="text" name="name" placeholder="Full Name" required >
    </label>
     </div>

<br>
          <div class="dob">
              <label>
                 <input type="date" name="dob" placeholder="Date of Birth" required>
              </label>
          </div>

<br>
          <div class="age">
   <label>
        <input type="number" name="age" placeholder="Age" required>
    </label>
</div>

      <div class="gender">
        <label for="gender" ></label>
        <select id="gender" name="gender" required>
            <option value="">Gender</option>
            <option value="male">Male</option>
            <option value="female">Female</option>
            <option value="other">Other</option>
        </select>
      </div>

<div class="phonenumber">

        <label for="phoneNumber"></label>
          <input type="tel" id="phoneNumber" name="phonenumber" placeholder="phone number" pattern="[0-9]{10}" maxlength="10" required>

</div>
<br>
          <div class="email_res">



      <label>
        <input type="email" name="mailid" placeholder="Email ID" required>
    </label>
<br>
          <br>
      <div class="box-2">

   <label>
        <input type="text" name="address" placeholder="Residential Address" required>
    </label>
          </div>
   </div>
<div class="dis">
<label for="district"></label>
    <select id="district" onchange="populateBranches()" required>
        <option value="" selected disabled >Select District</option>

  <option value="district1">Thiruvananthapuram</option>
  <option value="district2">Kollam</option>
  <option value="district3">Pathanamthitta</option>
  <option value="district4">Alappuzha</option>
  <option value="district5">Kottayam</option>
  <option value="district6">Idukki</option>
  <option value="district7">Ernakulam</option>
  <option value="district8">Thrissur</option>
  <option value="district9">Palakkad</option>
  <option value="district10">Malappuram</option>
  <option value="district11">Kozhikode</option>
  <option value="district12">Wayanad</option>
  <option value="district13">Kannur</option>
  <option value="district14">Kasaragod</option>
    </select>
</div>
      <div class="branch">
    <label for="branch"></label>
    <select id="branch" required>
        <option value="" selected disabled>Select Branch</option>
    </select>

    <script>

        const branchesByDistrict = {
            district1: ["Kazhakkoottam", "Neyyattinkara", "Varkala"],
district2: ["Punalur", "Kunnathur", "Kottarakkara"],
district3: ["Ranni", "Mallappally", "Pullad"],
district4: ["Cherthala", "Ambalappuzha", "Kuttanadu"],
district5: ["Vaikom", "Kaduthuruthy", "Kallara"],
district6: ["Adimaly", "Devikulam", "Nedumkandam"],
district7: ["Aluva", "Kochi", "Kanayannoor"],
district8: ["Thrissur", "Kunnamkulam", "Guruvayur"],
district9: ["Thrithala", "Pattambi", "Shornur"],
district10: ["Malappuram", "Mankada", "Perinthalmanna"],
district11: ["Vadakara", "Koyilandy", "Thamarassery"],
district12: ["Mananthavady", "Kalpetta", "Sulthanbathery"],
district13: ["Thalasseri", "Kannur", "Thaliparamba"],
district14: ["Adkathbail", "Adoor", "Adhur"]




        };

        function populateBranches() {
            // Get selected district
            const selectedDistrict = document.getElementById("district").value;


            const branchDropdown = document.getElementById("branch");


            branchDropdown.innerHTML = '<option value="" selected disabled>Select Branch</option>';


            if (selectedDistrict && branchesByDistrict[selectedDistrict]) {
                branchesByDistrict[selectedDistrict].forEach(branch => {
                    const option = document.createElement("option");
                    option.value = branch;
                    option.text = branch;
                    branchDropdown.appendChild(option);
                });
            }
        }
    </script>
      </div>
      <div class="ac">
        <label ></label>

      <select id="account_type" name="AccountType" required>
            <option value="">Account Type</option>
            <option value="male">Savings Account</option>
            <option value="female">Current Account</option>
            <option value="other">Joint Account</option>
            <option value="other">NRI Account</option>
        </select>

      </div>

      </div>
          <br>
        <label>Materials Provide</label>
        <div class="checkbox">
            <input type="checkbox" id="material1" name="materials_provide1" value="Material 1">
            <label for="material1">Debit Card</label><br>

            <input type="checkbox" id="material2" name="materials_provide2" value="Material 2">
            <label for="material2">Credit Card</label><br>

            <input type="checkbox" id="material3" name="materials_provide3" value="Material 3">
            <label for="material3">Cheque Book</label><br>
        </div>



<div class="button1">


        <button type="submit" class="btn btn-primary">Submit</button>
    <a href="{% url 'bankapp:logout' %}" class="btn btn-block">Logout</a>
</div>
</div>
  </form>

{% endblock %}

bankproject/templates/submit_form.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
 <div class="container mt-10 text-center">
    <div class="alert">
         <strong>Application successfully Registered</strong>
         <p>Thankyou for submitting your form</p>
     </div>
    <a href="{% url 'bankapp:home' %}" class="btn btn-success">Return to home page</a>

 </div>
{% endblock %}

bankproject/templates/success_page.html
{% extends 'base.html' %}
{% block content %}
    <div class=" mt-6 text-center">
    <a href="{% url 'bankapp:register_form' %}" class="btn btn-block">Click here to fill application form</a>
    </div>
{% endblock %}